KG: add test - get user
TerkaSlan/git_workshop_wta20 pull request #17
Opened 2024-11-28 11:54 UTC by KatarinaGenzli

pridala som testy na get user, ale či je to dobre, tak to netuším :D

2024-11-28 12:23 UTC, TerkaSlan requested changes
Ahoj,
testy su super, akurat svietia na cerveno, lebo nie su dobre zasadene v tom jsone - musia byt obalene este v "script" a "exec". Najjednoduchsie to opravis cez: 1) import json z main vetvy do postmana; 2) vyplnenie testov 3) export collection z postmana do toho isteho suboru v tvojej vetve. Dalej uz git add, ...

Takto sa postman postara o to aby ten json bol naformatovany sprave a nemusis to riesit ty manualne :)

2024-11-28 12:37 UTC, KatarinaGenzli commented
Ahoj Terka,

snažím sa importovať ten súbor do postmana, ale stále mi tam dáva že incorrect format, neviem kde robím chybu

2024-11-28 13:05 UTC, TerkaSlan commented
Ahoj,
ten ktory mas v tejto svojej vetve ti nepojde (prave kvoli tomu nedobremu jsonu). Skus sa prepnut do main vetvy, dat si git pull a presvedcit sa, ze tam nemas ziadne svoje zmeny (cez gitkraken na teba nic nove nesvieti). Potom importni v postmanovi. Kludne potom zaloz uplne novu vetvu a tuto ignoruj.

2024-11-28 17:48 UTC, KatarinaGenzli commented
skúsila som ešte raz, teraz to šlo importovať aj export urobiť, ale stále si nie som istá či je to OK

2024-11-28 18:41 UTC, TerkaSlan commented
Nevidim ziadnu zmenu oproti hlavnej vetve:
![image](https://github.com/user-attachments/assets/0c2865da-6d92-4f49-9163-0efb9fd0243a)
odstranila si akurat tie tvoje zmeny predtym.

Teraz by kazdopadne tvoja branch mala byt pripravena na pridanie testov :)

2024-11-28 19:01 UTC, KatarinaGenzli commented
tak snáď teraz už to tam je, pridala som test do delete user

2024-11-29 09:25 UTC, TerkaSlan approved these changes
Skvela praca :)

2024-11-29 18:53 UTC, merged